package ekomp.Models;

public enum PersonType {
    BOSS,
    VENDOR,
    SERVICETECHNICIAN,
    CLIENT,
    BOSS_VENDOR,
    BOSS_SERVICETECHNICIAN,
    BOSS_CLIENT,
    VENDOR_CLIENT,
    SERVICETECHNICIAN_CLIENT,
    BOSS_VENDOR_CLIENT,
    BOSS_SERVICETECHNICIAN_CLIENT
}
